# Generated by Django 3.0.4 on 2020-03-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='en', max_length=6, verbose_name='Language'),
        ),
    ]
