# Generated by Django 3.1.4 on 2021-01-30 09:54

import uuid
from django.db import models, migrations

import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210130_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingaction',
            name='id',
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='category',
            field=models.CharField(choices=[('confirm_email', 'Confirm e-mail'), ('reset_password', 'Reset Password'), ('verify_phone_number', 'Verify Phone Number')], db_index=True, max_length=50),
        ),
    ]
