# -*- encoding: utf-8 -*-

from config.settings.components import env

GOOGLE_CLIENT_ID = env('GOOGLE_CLIENT_ID')

DJANGO_ADMIN_SSO_OAUTH_CLIENT_ID = env('ADMIN_GOOGLE_OAUTH_CLIENT_ID')
DJANGO_ADMIN_SSO_OAUTH_CLIENT_SECRET = env('ADMIN_GOOGLE_OAUTH_CLIENT_SECRET')

FACEBOOK_CLIENT_ID = env('FACEBOOK_CLIENT_ID')
FACEBOOK_CLIENT_SECRET = env('FACEBOOK_CLIENT_SECRET')
