name: Django CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim-buster
      volumes:
      - /cache/pip:/github/home/.cache/pip
    services:
      redis:
        image: redis:5
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: circleci/postgres:12-ram
        env:
          POSTGRES_HOST: 'postgres'
          POSTGRES_DB: 'postgres'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: /github/home/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/common.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install System Depedencies
      run: |
        apt-get update && apt-get install -y build-essential libpq-dev binutils libproj-dev gdal-bin
    - name: Install Project Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/common.txt
        pip install -r requirements/testing.txt
    - name: Run Tests
      run: |
        pytest
      env:
        DJANGO_ENV: 'testing'
        DJANGO_HOSTNAME: 'http://test.server'
        GOOGLE_CLIENT_ID: 'google_client_id'
        GOOGLE_CLIENT_SECRET: 'google_client_secret'
        FACEBOOK_CLIENT_ID: 'facebook_client_id'
        FACEBOOK_CLIENT_SECRET: 'facebook_client_secret'
        ADMIN_GOOGLE_OAUTH_CLIENT_ID: 'admin_google_oauth_client_id'
        ADMIN_GOOGLE_OAUTH_CLIENT_SECRET: 'admin_google_oauth_client_secret'
        POSTGRES_HOST: 'postgres'
        POSTGRES_DB: 'postgres'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_PORT: 5432
        TWILIO_ACCOUNT_SID: 'twilio_account_sid'
        TWILIO_AUTH_TOKEN: 'twilio_auth_token'
        TWILIO_PHONE_NUMBER: 'twilio_phone_number'
